import { useState } from "react";
import { useNavigate } from "react-router-dom";
import FileUploader from "../components/FileUploader";
import { useScan } from "../context/ScanContext";
import { uploadScan } from "../services/api";

/**
 * UploadPage — Upload scan_results.json, preview, and send to backend.
 */
export default function UploadPage() {
  const navigate = useNavigate();
  const { storeScanResults, isLoading, setIsLoading, error, setError } =
    useScan();
  const [parsedData, setParsedData] = useState(null);

  const handleFileLoaded = (data) => {
    setParsedData(data);
    setError(null);
  };

  const handleSubmit = async () => {
    if (!parsedData) return;

    setIsLoading(true);
    setError(null);

    try {
      const results = await uploadScan(parsedData);
      storeScanResults(results);
      navigate("/results");
    } catch (err) {
      setError(err.message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto px-4 py-10">
      <h1 className="text-xl font-bold mb-1">Upload Scan Results</h1>
      <p className="text-sm text-gray-500 mb-6">
        Upload the <code>scan_results.json</code> file generated by the IoTriage
        scanner. The backend will parse devices, look up CVEs, and generate
        mitigations.
      </p>

      <FileUploader onFileLoaded={handleFileLoaded} isLoading={isLoading} />

      {/* Preview */}
      {parsedData && (
        <div className="mt-4 border border-gray-200 rounded p-4">
          <p className="text-sm font-medium mb-2">
            Preview ({parsedData.length} device
            {parsedData.length !== 1 ? "s" : ""} found)
          </p>
          <pre className="text-xs text-gray-600 bg-gray-50 rounded p-3 max-h-40 overflow-y-auto">
            {JSON.stringify(parsedData.slice(0, 2), null, 2)}
            {parsedData.length > 2 &&
              `\n\n... and ${parsedData.length - 2} more devices`}
          </pre>
        </div>
      )}

      {/* Error */}
      {error && (
        <div
          className="mt-4 border border-red-300 bg-red-50 rounded p-3 text-sm text-red-700"
          role="alert"
        >
          Error: {error}
        </div>
      )}

      {/* Submit */}
      <div className="mt-6">
        <button
          onClick={handleSubmit}
          disabled={!parsedData || isLoading}
          className="border border-gray-400 hover:border-black disabled:opacity-40 disabled:cursor-not-allowed text-black px-6 py-2 rounded text-sm font-medium"
        >
          {isLoading ? "Analyzing..." : "Analyze Scan"}
        </button>
      </div>
    </div>
  );
}
